### PR TITLE
Removal of content-type feature from library for now as no longer par…

### PR DESCRIPTION
**Pull request by jonathanKingston**
…t of the spec. Bump package version.

### CODE REVIEW

**Comment by neftaly** [comment]
Hey, thanks again! Could you please remove content-type handling outright? Then we can close #3!

**Comment by neftaly** [comment]
I've added you as a collaborator, hope you don't mind :) Just make sure to request a review before pushing anything, hah.

**Comment by jonathanKingston** [comment]
@neftaly thank you! Sure will do in the WebAppSec meeting right now. Will fix later.

**Comment by jonathanKingston** [comment]
@neftaly or @fmarier would you be able to review this? (It fixes a console error in Chrome unstable on srihash.org)

I'm not sure if you wish to bump the version to `0.2.0` in regards to this being a change of features and also fixing the unicode issue too.

**Comment by fmarier** [comment]
Looks good to me, except I would go for 0.2.0 because it's not just a bugfix, it feels like a new thing.

**Comment by neftaly** [comment]
Published, thanks!

**Pull request merged**
