### PR TITLE
Adding in basic cli usage of sri-toolbox

### PR DESCRIPTION
**Pull request by jonathanKingston**
Just basic usage to give quick CLI access (will add more later for flags and help etc)

### CODE REVIEW

**Comment by josephpage** [comment]
Good idea ! :+1:

**Comment by jonathanKingston** [comment]
@neftaly do you like this being here or would you prefer as a separate npm?

**Comment by neftaly** [comment]
Oop, sorry - I've been using slack notifications, and didn't realize they haven't been working for personal repos. LGTM - but add in some tests later for extra credit :)

**Comment by jonathanKingston** [comment]
@neftaly thanks for this totally missed it.

Yeah I will do, I was going to provide more help too with other benefits.

**Pull request merged**
