### PR TITLE
Adding in code of conduct from: http://contributor-covenant.org/

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by neftaly** [comment]
I'm ambivalent on this... up to you if you want to merge :)

**Comment by jonathanKingston** [comment]
@neftaly I'm in a similar state too so it was merely a suggestion. A decent open code of conduct is something I see as important for all projects however I can see that pushing out decent contributors to be potentially counter intuitive and squashing someone else's free speech also (I might carry privileged views that I am still trying to understand in this field and I'm not a expert here).

Anyway I would like to hear your conflicting views as they might be something we can contribute back perhaps (or have a less restrictive policy perhaps)?

**Comment by neftaly** [comment]
"Don't be an asshat" should be implicit. If your only reason to act like an adult is because there is a contract specifically enforcing a rule that you do so, well, you're doing it wrong :P

But again, I really don't have a strong opinion either way.

**Comment by jonathanKingston** [comment]
@neftaly ok my objections seem far more political than that around dropping lib writers from a project because of their views could become a witch hunt; or a Tim Hunt perhaps?

I have strong views of free speech and also advocating "don't be an asshat" conflicting here.

Perhaps @fmarier could say how he feels?

I care mostly as I like people to share views and make the web a better place.

**Comment by jonathanKingston** [comment]
@neftaly and @fmarier how about: https://www.mozilla.org/en-US/about/governance/policies/participation/ instead? It seems as/more robust anyway.

Rust covers it in their contributing:
https://github.com/servo/servo/blob/master/CONTRIBUTING.md

**Comment by jonathanKingston** [comment]
It's safe to say there isn't consensus on this etc and that is fine.
I'm closing this but happy to reopen at a later date etc.

**Pull request closed without merging**
