### PR TITLE
Add "full" option

### PR DESCRIPTION
**Pull request by neftaly**
@fmarier any chance you could please take a look?

### CODE REVIEW

**Comment by fmarier** [comment]
I don't understand that the `full` option does. Is it for adding the charset to the integrity attribute? (something that's not in the spec)

**Comment by neftaly** [comment]
Hmm, I put it in readme.md, but it doesn't have appeared to stuck. Will push again.

**Comment by neftaly** [comment]
Ok, it should be fixed. Something messed up on GH's end, so I re-amended.

**Comment by fmarier** [comment]
I'm still unsure about what it means or does. Is it about splitting the integrity attribute and returning its components separately?

**Comment by neftaly** [comment]
More-or-less, it returns all the parts used to build the integrity attribute, as well as the integrity attribute as well. That way you can access stuff like raw SHA hashes and the filtered content-type.

Ref [mozilla/srihash.org/#46](https://github.com/mozilla/srihash.org/pull/46#issuecomment-76558669)

**Comment by fmarier** [comment]
It might be worth putting that explanation into the README, I may not be the only one confused by the original description.

**Comment by neftaly** [comment]
Howzat? I can bump neftaly/handlebars-helper-sri to 0.0.1 if this merges :)

**Comment by neftaly** [comment]
Howzat? I can bump neftaly/handlebars-helper-sri to 0.0.1 if this merges :)

**Comment by fmarier** [comment]
LGTM

**Comment by neftaly** [comment]
Thanks man

**Pull request merged**
